// import React from 'react'

// export function App() {
//     const[newItem, setNewItem] = useState("")
//     const [todos, setTodos] =useState([])
    
  
//     function handleSubmit(e) {
//       e.preventDefault()
  
//       setTodos(currentTodos => { 
//         return( [...currentTodos,
        
//        {id:crypto.randomUUID(),
//          title: newItem, completed: false},
//         ])
//     })
//     setNewItem("")
//   }
// }